# Generated by Django 4.1.2 on 2023-01-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
