# Generated by Django 4.1.2 on 2023-01-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_serialnumber_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='serialNumber',
            field=models.CharField(max_length=50),
        ),
    ]
