# Generated by Django 4.1.2 on 2023-01-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_serialnumber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SerialNumber',
        ),
    ]
